version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: six-cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_ROOT_USER: mongo
      MONGO_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/